Cleanup test action

diff --git a/.github/workflows/check-setup.yml b/.github/workflows/check-setup.yml
--- a/.github/workflows/check-setup.yml
+++ b/.github/workflows/check-setup.yml
@@ -30,12 +30,10 @@ jobs:
         run: node ace configure adonisjsx
         working-directory: ./app
 
-      - name: Setup app
+      - name: Setup app code
         run: |
           cp -f repository/.github/stubs/tsconfig.stub app/tsconfig.json
           cp -f repository/.github/stubs/routes.stub app/start/routes.ts
-          cp -f repository/.github/stubs/test-server.sh app/test-server.sh
-          chmod +x app/test-server.sh
 
       - uses: JarvusInnovations/background-action@v1
         name: Setup test server
@@ -47,6 +45,13 @@ jobs:
           log-output-if: failure
           working-directory: app
 
-      - name: Check if everything is working
-        run: ./test-server.sh
-        working-directory: ./app
+      - name: Check if app responds
+        run: |
+          response=$(curl -o /dev/null -s -w "%{http_code}\n" -X GET http://localhost:3333)
+          if [ "$response" -eq 200 ]; then
+              echo "Success!"
+              exit 0
+            else
+              echo "Failed with status $response."
+              exit 1
+          fi
